### ISSUE TITLE
[Bug]: Trait method 'activities' will not be applied because it collides with 'LogsActivity'

### ISSUE THREAD

**Issue by majdghithan** [edwink75/filament-user-activity#7]
### What happened?

Trait method 'activities' will not be applied because it collides with 'LogsActivity' when adding the trait to user model

### How to reproduce the bug

add the trait to user model

### Package Version

2

### PHP Version

8.2

### Laravel Version

10

### Which operating systems does with happen with?

macOS

### Notes

https://github.com/edwink75/filament-user-activity/issues

**Comment by edwink75** [comment]
Can you give me a little more details about the conflicting plugin you're using? And more details about the error?

**Comment by majdghithan** [comment]
z3d0x/filament-logger

**Comment by edwink75** [comment]
Thanks for reporting. I added the package to the conflict section of composer.

**Comment by edwink75** [comment]
Added to composer
