### ISSUE TITLE
[Bug]: Compatibility with laravel 11

### ISSUE THREAD

**Issue by andre-silvakmm** [edwink75/filament-user-activity#9]
### What happened?

The pkg is not compatible with laravel 11

### How to reproduce the bug

Install the pkg in laravel 11

### Package Version

1.0.8

### PHP Version

8.2

### Laravel Version

11.1.1

**Comment by edwink75** [comment]
Forgot to answer here :1st_place_medal: 
The plugin is now compatible with Laravel 11 with version 1.0.9 and eventually later versions
https://github.com/edwink75/filament-user-activity/releases/tag/1.0.9

**Comment by edwink75** [comment]
See above
